[build]
  publish = "dist/public"
  command = "npm install && npx vite build"

[build.environment]
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api?path=:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "drizzle-orm"]